### ISSUE TITLE
Error: 'Class Connect failed to load.

### ISSUE THREAD

**Issue by khurshid-alam** [bndr/imgur-php-wrapper#7]
I downloaded the zip, uploaded the code on my web-server, set the redirect uri on the imgur website, and then used following code:

```php
<?php
/**
 * PHP Imgur wrapper 0.1
 * Imgur API wrapper for easy use.
 * @author Vadim Kr.
 * @copyright (c) 2013 bndr
 * @license http://creativecommons.org/licenses/by-sa/3.0/legalcode
 */

//Include the main file
include("Imgur.php");
//Set up your api key and secret
$api_key = "bxxxxxxxxxxxx";
$api_secret = "fff490eae26e046fb8xxxxxxxxxxxxxxxxxxxx";

$imgur = new Imgur($api_key, $api_secret);


/*-----------------------------------------------------------------------------------*/
/* Authorization
/*-----------------------------------------------------------------------------------*/
//We create a new instance of imgur class.
// Imgur oAuth will return code as GET parameter after the user allows access
if (isset($_GET['code'])) {
    $tokens = $imgur->authorize(false, $_GET['code']); //First parameter is for refresh_tokens
    //The user is authorized. You can save the $tokens['refresh_token'] and $tokens['access_token'] for future use;
} else {
    // GET parameter doesn't exist, so we will have to ask user to allow access for our application
    $imgur->authorize();
}

print_r($tokens['refresh_token']);
echo "\n";
print_r($tokens['access_token']);
exit();
```

But whenever I run it it gives me following error
```
PHP Fatal error:  Uncaught exception 'Exception' with message 'Class Connect failed to load. Please verify that you uploaded the files correctly.' in /app/imgur/Imgur.php:12
Stack trace:
#0 [internal function]: {closure}('Connect')
#1 /app/imgur/Imgur.php(51): spl_autoload_call('Connect')
#2 /app/imgur/oauth.php(16): Imgur->__construct('bd583xxxxx', 'fff490.......................')
#3 {main} thrown in /app/imgur/Imgur.php on line 12
```

Php version > 5.5.9

Any idea?

**Comment by fxcosta** [comment]
With this pr #8 this error is fixed.
